import { NgModule } from '@angular/core';
import { NativeScriptRouterModule } from 'nativescript-angular/router';
import { Routes } from '@angular/router';

import { AutoGeneratedComponent } from './auto-generated/auto-generated.component';
import { RegionsComponent } from './world/regions/regions.component';
import { CountriesComponent } from './world/countries/countries.component';
import { CountryComponent } from './world/country/country.component';
import { NotFoundComponent } from './not-found/not-found/not-found.component';

export const routes: Routes = [
  { path: 'home', component: RegionsComponent },
  { path: '', redirectTo: 'home', pathMatch: 'full' },
  { path: 'countries/:filter/:filterName', component: CountriesComponent },
  { path: 'country/:countryName', component: CountryComponent },
  { path: '**' ,component: NotFoundComponent}
];

@NgModule({
  imports: [NativeScriptRouterModule.forRoot(routes)],
  exports: [NativeScriptRouterModule]
})
export class AppRoutingModule { }
